In [1]:
import pandas as pd

In [2]:
df_datos= pd.read_csv("dataset_incompleto.csv")
df_datos = df_datos.drop(columns= ["Unnamed: 0"])
df_datos.head(3)

,DPA_PARROQ,DPA_DESPAR,altura_mean,altura_min,altura_max,pendiente_mean,distancia_rios,precipitaciones_mean,DPA_DESPRO,DPA_DESCAN,num_inundaciones,riesgo_inundacion
0,010150,CUENCA,2548.790629,2331,2863,89.428921,1110.917269,73.119566,AZUAY,CUENCA,0.0,Nulo
1,010151,BANOS,3492.725017,2569,4136,89.902887,819.428420,78.623622,AZUAY,CUENCA,1.0,Bajo
2,010152,CUMBE,3006.112686,2620,3477,89.977973,1149.323612,65.115401,AZUAY,CUENCA,1.0,Bajo

In [3]:
df_datos.shape

(1050, 12)

In [4]:
df_densidad = pd.read_csv("densidad_poblacional.csv", dtype= {"DPA_PARROQ": str})
df_densidad = df_densidad.dropna()
# df_densidad = df_densidad.drop(columns=["fid"])
df_densidad["DPA_PARROQ"] = df_densidad["DPA_PARROQ"].astype(str)

df_densidad.head()

  DPA_PARROQ  Densidad Poblacional
0     010150                 5.044
1     010151                87.000
2     010152                86.000
3     010153                 5.000
4     010154                29.000

In [5]:
df_densidad.shape

(1040, 2)

In [6]:
df_final = df_datos.merge(
    df_densidad[
        ["DPA_PARROQ", "Densidad Poblacional"]
    ],
    on=["DPA_PARROQ"],
    how="left"
)
df_final.head(3)

,DPA_PARROQ,DPA_DESPAR,altura_mean,altura_min,altura_max,pendiente_mean,distancia_rios,precipitaciones_mean,DPA_DESPRO,DPA_DESCAN,num_inundaciones,riesgo_inundacion,Densidad Poblacional
0,010150,CUENCA,2548.790629,2331,2863,89.428921,1110.917269,73.119566,AZUAY,CUENCA,0.0,Nulo,5.044
1,010151,BANOS,3492.725017,2569,4136,89.902887,819.428420,78.623622,AZUAY,CUENCA,1.0,Bajo,87.000
2,010152,CUMBE,3006.112686,2620,3477,89.977973,1149.323612,65.115401,AZUAY,CUENCA,1.0,Bajo,86.000

In [7]:
df_final.shape

(1050, 13)

In [8]:
df_final.isnull().sum()

DPA_PARROQ               0
DPA_DESPAR               0
altura_mean              0
altura_min               0
altura_max               0
pendiente_mean           0
distancia_rios           0
precipitaciones_mean     8
DPA_DESPRO               0
DPA_DESCAN               0
num_inundaciones         0
riesgo_inundacion        0
Densidad Poblacional    10
dtype: int64

In [9]:
df_final.shape

(1050, 13)

In [10]:
df_final.to_csv("dataset.csv")